version: '2'
services:
  ss-tproxy:
      # 镜像的路径
    image: yahuiwong/ss-tproxy:3.1.0
    privileged: true
    volumes:
      - ./conf/ss-tproxy.conf:/etc/ss-tproxy/ss-tproxy.conf
      - ./conf/ssr-local.json:/etc/ss-tproxy/ssr-local.json
      - /lib/modules/4.19.2-1.el7.elrepo.x86_64/:/lib/modules/4.19.2-1.el7.elrepo.x86_64/
    restart: always
        # 容器名称
    container_name: ss-tproxy
