# 拉取 CentOS
#FROM hub.c.163.com/library/centos:latest
FROM yahuiwong/centos:7.6.1810.5.2.11-1.el7.elrepo.x86_64
# 维护者
MAINTAINER YahuiWong <yahui9119@live.com>

COPY install-ss-tproxy.temp.sh /install-ss-tproxy.temp.sh
RUN sh /install-ss-tproxy.temp.sh
